spring:
  application:
    name: spring-boot-demo
  profiles:
    active: local
  redis:
    host: localhost
    port: 6379
server:
  port: 8080
---
server.port: 7800
database: h2

spring:
  profiles: local
  datasource:
    hikari:
      maximum-pool-size: 24
    schema: classpath*:db/${database}/schema.sql
#    data: classpath*:db/${database}/data.sql
    jpa:
      show_spl: true
      properties:
        hibernate:
          format_sql: true
    h2:
      console:
        enabled: true

spring.jpa.hibernate.ddl-auto: none
spring.datasource.initialization-mode: always
logging:
  level:
    org:
      springframework.web: debug