CREATE TABLE member
(
    member_seq  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    member_id VARCHAR(32) NOT NULL ,
    member_name VARCHAR(128),
    CONSTRAINT pk_author PRIMARY KEY (member_seq)
);
